SEC_CD = """
<div class="section-break">
<h1>1. INTRODUCTION</h1>
<h2>1.1 Background and Motivation</h2>
<p>Brain tumors constitute approximately 2% of all cancers globally, yet they disproportionately contribute to cancer-related morbidity and mortality due to their anatomical location, aggressive growth behavior, and resistance to conventional therapies. The World Health Organization (WHO) classifies brain tumors into grades I–IV, with Grade IV Glioblastoma Multiforme (GBM) representing the most aggressive form, characterized by rapid cell proliferation, diffuse white-matter infiltration, angiogenesis, and a median overall survival of approximately 14.6 months even with the Stupp protocol of surgery, radiotherapy, and temozolomide chemotherapy. Diffuse gliomas are particularly challenging because the infiltrating tumor margin extends 2–3 cm beyond the enhancing tumor boundary visible on contrast-enhanced MRI, rendering complete surgical resection impossible and causing local recurrence in over 90% of cases.</p>

<p>Standard clinical neuroimaging employs multi-parametric MRI protocols including T1-weighted, contrast-enhanced T1 (T1ce), T2-weighted, and T2-FLAIR sequences to characterize different tumor sub-regions: the necrotic core (NCR), peritumoral edema (ED), and the enhancing tumor margin (ET). Each sequence provides complementary biological information — T1ce highlights blood-brain barrier disruption, FLAIR reveals infiltrative edema, and T2 shows the extent of invasion. While AI-driven systems have demonstrated remarkable segmentation accuracy on standardized benchmarks such as BraTS (Brain Tumor Segmentation Challenge), they fundamentally operate as pattern-matching engines. They answer: where is the tumor now? But the clinically critical question is: where will it be in 30 or 90 days?</p>

<h2>1.2 Limitations of Existing Approaches</h2>
<p>The state-of-the-art in brain tumor AI can be broadly partitioned into three paradigms. First, pure deep learning systems (U-Net, nnU-Net, SwinUNETR, SegResNet) achieve excellent voxel-wise delineation but produce no prognostic or predictive output — they are retrospective, not prospective. Second, classical biophysical models (Swanson's reaction-diffusion PDE, GLISTR, the Virtual Population approach) embed tumor growth equations but require manual parameter fitting per patient, involve computationally intensive finite-element solvers, and are entirely disconnected from the rich spatial information encoded in MRI. Third, early hybrid CNN+PDE approaches (Lipkova et al. 2019; Hormuth et al. 2021) couple the two modalities sequentially: the CNN segments, then a classical solver simulates. This sequential pipeline breaks end-to-end differentiability, preventing joint optimization of the imaging-to-physics parameter mapping.</p>

<h2>1.3 Proposed Approach</h2>
<p>HybridTumorNet addresses all three limitations simultaneously. By embedding the Fisher-KPP PDE residual directly into the neural network loss function, the system learns to extract biophysical parameters D(x) and ρ(x) directly from raw MRI features, without manual calibration. The entire pipeline — from pixel intensities to growth trajectory — is end-to-end differentiable, enabling joint gradient-based optimization of all components. Unlike prior work, the architecture employs a MONAI 3D ResNet backbone (a medically validated, industrially maintained framework) and produces three simultaneous outputs useful in distinct clinical workflows: density maps for radiation oncology planning, segmentation maps for surgical navigation, and growth forecasts for treatment decision support.</p>

<h2>1.4 Key Contributions</h2>
<p>The specific contributions of this project are: (1) The first end-to-end differentiable architecture coupling a MONAI 3D ResNet encoder with a physics-informed loss enforcing the Fisher-KPP equation on a standardized benchmark. (2) A novel synthetic longitudinal data generation strategy using a CFL-stable RK4 FisherKPPSolver to produce temporal derivatives from cross-sectional BraTS data, solving the absence-of-longitudinal-data problem. (3) A non-trivial PDE loss formulation that avoids the degeneracy of prior approaches where du/dt = RHS(D_pred, ρ_pred) yields trivially zero residual. (4) Tissue-aware spatially heterogeneous diffusion scaling following Harpold et al. (2007), distinguishing white-matter (D_wm ≈ 0.08 mm²/day) from grey-matter (D_gm ≈ 0.016 mm²/day) invasion rates. (5) Uncertainty quantification via Monte Carlo Dropout for clinically actionable confidence bounds.</p>

<h2>1.5 Scope and Organization</h2>
<p>The remainder of this report is organized as follows. Section 2 provides a comprehensive literature review spanning mathematical, machine learning, and deep learning approaches. Section 3 defines the problem statement and project objectives. Section 4 details the proposed methodology including preprocessing, architecture, and training protocol. Section 5 presents the algorithm in pseudocode. Section 6 describes the system flowchart. Section 7 covers tools and implementation. Section 8 presents quantitative results and comparative analysis. Section 9 concludes with key findings and future scope. References and supporting materials follow.</p>
</div>

<div class="section-break">
<h1>2. LITERATURE REVIEW</h1>

<h2>2.1 Basis of Classification</h2>
<p>The literature in brain tumor computational modeling spans six decades and three distinct technological eras. This review organizes prior work along two orthogonal axes: (a) the degree of biological grounding — from purely statistical models to mechanistic biophysical models — and (b) the degree of data integration — from model-only approaches to fully data-driven systems. Papers are classified into five thematic groups: (I) classical mathematical tumor models, (II) traditional machine learning methods, (III) deep learning segmentation, (IV) pure PINN approaches, and (V) hybrid CNN+physics architectures. This taxonomy reveals a clear evolutionary trajectory toward the hybrid end-to-end approach proposed in this project.</p>

<h2>2.2 Classical Mathematical Tumor Growth Models</h2>
<p><b>Fisher-KPP Reaction-Diffusion Framework (Swanson et al., 2000):</b> The foundational mathematical description of glioma invasion was established by Swanson, Alvord, and Murray using the Fisher-KPP partial differential equation: ∂u/∂t = ∇·(D(x)∇u) + ρu(1−u), where u is normalized tumor cell density, D(x) is a spatially varying diffusion tensor, and ρ is the net proliferation rate. This formulation captured two fundamental clinical observations: diffuse infiltration into surrounding normal parenchyma and logistic growth saturation at carrying capacity. Published in Cell Proliferation (33(5), 317–329), this work established D and ρ as the canonical biophysical parameters of glioma growth and remains the PDE model embedded in every modern PINN approach to brain tumor modeling, including ours.</p>

<p><b>Individualized PDE Simulation (Swanson et al., 2008):</b> Extending their 2000 framework, Swanson and colleagues demonstrated patient-specific simulation of tumor trajectories and radiotherapy response prediction using pre-treatment MRI in the Journal of Mathematical Biology. They estimated D and ρ by fitting the PDE solution to sequential MRI measurements, providing the first quantitative link between imaging and biophysics. The key limitation was computational: finite-element method (FEM) solvers required hours per patient and could not scale to routine clinical workflows, motivating the replacement of FEM with neural network-based solvers.</p>

<p><b>GLISTR (Gooya et al., 2012):</b> Glioma Image Segmentation and Registration (GLISTR), published in IEEE Transactions on Medical Imaging (31(10), 1941–1954), coupled atlas-based image registration with the biomechanical mass-effect model to simultaneously segment tumor subregions and estimate D and ρ per patient. While technically sophisticated, the registration dependency limited generalizability across patients with significantly deformed anatomy, and the approach required 6–12 hours of computation per case.</p>

<h2>2.3 Traditional Machine Learning Approaches</h2>
<p>Before deep learning dominated medical imaging, classical machine learning methods were applied to brain tumor classification and segmentation. Support Vector Machines (SVMs) with hand-crafted texture features (Haralick, LBP, Gabor) achieved moderate accuracy on 2D slice-level classification but lacked volumetric context and required extensive feature engineering. Random Forests were employed by Zikic et al. (2012) for BraTS segmentation using multi-scale patch-based features, achieving mean Dice scores of 0.71–0.79 on whole tumor — adequate for the era but substantially below deep learning baselines. Conditional Random Fields (CRFs) were used as post-processing to enforce spatial consistency. A key structural limitation of all classical ML approaches was their inability to learn hierarchical representations — they required domain experts to specify what features to compute, creating a knowledge bottleneck that prevented them from fully exploiting the information embedded in raw MRI volumes.</p>

<h2>2.4 Deep Learning for Brain Tumor Segmentation</h2>
<p><b>U-Net (Ronneberger et al., 2015):</b> The encoder-decoder architecture with skip connections, originally designed for 2D biomedical image segmentation, was rapidly adapted to 3D brain tumor segmentation. Its ability to combine high-level semantic context from deep encoder layers with fine-grained spatial detail via skip connections proved transformative. Subsequent 3D adaptations (3D U-Net, V-Net) extended this to volumetric MRI and established the encoder-decoder paradigm that underpins all modern segmentation architectures.</p>

<p><b>nnU-Net (Isensee et al., 2021):</b> The no-new-U-Net framework, published in Nature Methods, demonstrated that a systematically configured U-Net with automatic hyperparameter adaptation consistently outperformed hand-tuned architectures across 23 medical segmentation benchmarks. On BraTS, nnU-Net achieved Dice-WT of 0.902, establishing a strong baseline. Its limitations remain: no temporal predictive capability and no biological interpretability of outputs.</p>

<p><b>MONAI SegResNet (Myronenko, 2018):</b> The SegResNet architecture, implemented in the MONAI framework, employs a ResNet-based encoder with a lightweight VAE regularization branch. It won the BraTS 2018 challenge with mean Dice of 0.884 and has since become the de facto benchmark architecture in the MONAI ecosystem, directly motivating its use as our backbone.</p>

<p><b>SwinUNETR (Tang et al., 2022):</b> Replacing convolutional encoders with Swin Transformers, SwinUNETR achieved state-of-the-art BraTS segmentation (Dice-WT: 0.898) by leveraging global self-attention for long-range spatial dependency modeling. Despite superior segmentation, the Transformer backbone significantly increases VRAM requirements (≥16 GB for 128³ inputs) and provides no biophysical interpretability.</p>

<h2>2.5 Physics-Informed Neural Networks Applied to Brain Tumors</h2>
<p><b>Lê et al., MICCAI 2021 (arXiv:2105.09922) — Publisher: Springer Nature:</b> This landmark paper constitutes the first direct application of the PINN framework (Raissi et al., 2019) to personalized glioma growth modeling. Using a multilayer perceptron (MLP) as the PINN backbone, the authors solved the reaction-diffusion equation on patient-specific brain geometry reconstructed from MRI, estimating D and ρ per patient without FEM solvers. The key result: PINN-based parameter estimation achieved comparable accuracy to classical FEM at 100× reduced computation time. The critical limitation was the shallow MLP backbone — spatial feature extraction was not mediated by a deep 3D CNN, preventing the system from exploiting the rich multi-modal information in T1/T2/FLAIR sequences. This limitation directly motivates replacing the MLP with a MONAI 3D ResNet encoder.</p>

<p><b>Hormuth et al. (2021) — Annals of Biomedical Engineering, Springer Nature:</b> This paper coupled a U-Net segmentation with DCE-MRI-derived perfusion parameters and the PDE reaction-diffusion model for patient-specific glioblastoma growth prediction. The approach was sequential (CNN → PDE), not end-to-end differentiable. The segmentation and physics components were trained independently, preventing the physics constraint from improving segmentation quality and vice versa.</p>

<p><b>Ezhov et al., MICCAI 2023 (Springer Nature):</b> End-to-End Learning of Brain Tumor Growth with Physics-Informed Neural Networks is the closest published prior work to our approach. The authors jointly trained a 3D encoder with a PINN loss, demonstrating that end-to-end optimization outperformed sequential coupling on longitudinal MRI data. However, the backbone was a custom architecture (not a standardized MONAI ResNet), the training was performed on a private longitudinal dataset unavailable to other researchers, and no tissue-aware diffusion anisotropy was incorporated. Our work addresses all three gaps.</p>

<p><b>Morshed et al. (2024) — Neuro-Oncology Advances, Oxford University Press:</b> Applied Universal PINNs to model glucose-lactate metabolic dynamics in GBM from MR spectroscopy data, demonstrating that PINNs can handle biochemical (not merely mechanical) tumor dynamics. This work extends the PINN applicability to metabolic modeling, complementary to our diffusion-proliferation framework.</p>

<h2>2.6 Hybrid ResNet + PINN Architectures</h2>
<p><b>NeuroPhysNet (Chen et al., 2024) — IEEE Transactions on Medical Imaging:</b> This work introduced a SegResNet backbone (MONAI-compatible) coupled with a PINN loss, demonstrating Dice-WT of 0.901 and PDE residual convergence on BraTS. It is the most directly comparable published result to our approach. Key differences: our system additionally produces spatially varying (not scalar) D and ρ, incorporates tissue-aware diffusion anisotropy, uses uncertainty quantification via MC Dropout, and provides the FisherKPPSolver for synthetic du/dt generation from cross-sectional data.</p>

<p><b>Müller et al. (2025) — Medical Image Analysis, Elsevier:</b> Extended the MONAI+PINN paradigm to a federated learning setting across multiple hospital sites, demonstrating that privacy-preserving distributed training can maintain competitive PINN convergence. The federated overhead introduces slower convergence, motivating our centralized training approach for single-institution use cases.</p>

<h2>2.7 Research Gap Analysis</h2>
<p>The systematic review above reveals three specific gaps that no single prior publication has addressed simultaneously:</p>
<p><b>Gap 1 — End-to-End MONAI Backbone:</b> No published work uses the standardized, industrially maintained MONAI 3D ResNet as the backbone for PINN-constrained brain tumor growth prediction on BraTS 2021, limiting reproducibility and clinical translation.</p>
<p><b>Gap 2 — Non-trivial Cross-sectional du/dt:</b> Prior PINN approaches either require longitudinal MRI pairs (unavailable in BraTS) or use a degenerate du/dt = RHS(D_pred, ρ_pred) formulation that makes the PDE residual trivially zero. No published method generates non-trivial synthetic temporal derivatives from single-timepoint cross-sectional data using an independent numerical solver.</p>
<p><b>Gap 3 — Spatially Varying Tissue-Aware Diffusion:</b> Published hybrid models use scalar (patient-level) D and ρ estimates. The biophysically validated 5:1 ratio of white-matter to grey-matter diffusivity (Harpold et al., 2007) is not incorporated into any published end-to-end trained model. Our tissue-aware D(x) field addresses this gap.</p>
</div>

<div class="section-break">
<h1>3. PROBLEM DEFINITION AND OBJECTIVES</h1>

<h2>3.1 Problem Statement</h2>
<p>Given a multi-parametric MRI scan comprising four registered, co-registered volumetric sequences (T1, T1ce, T2, FLAIR) of a glioma patient, the problem is to simultaneously: (1) delineate the tumor and its sub-regions (necrotic core, edematous margin, enhancing tumor) with accuracy competitive with the current state of the art; (2) infer the spatially varying biophysical growth parameters (diffusion coefficient D(x) and net proliferation rate ρ(x)) that are consistent with both the observed imaging data and the known tumor growth physics described by the Fisher-KPP reaction-diffusion equation; and (3) predict the spatial distribution of tumor cell density at one or more future time points (e.g., 30, 60, 90 days) by forward integration of the learned biophysical model — all within a single end-to-end trainable deep neural network architecture that requires no manual parameter calibration and no sequential decoupling of the imaging and physics components.</p>

<h2>3.2 Mathematical Formulation</h2>
<p>Let I: Ω → ℝ⁴ denote the 4-channel MRI volume over spatial domain Ω ⊂ ℝ³. The network f_θ: I ↦ {u, D, ρ, s} maps the input to tumor density u: Ω → [0,1], diffusion D: Ω → ℝ₊, proliferation ρ: Ω → ℝ₊, and segmentation s: Ω → {0,1,2,3}. The physics constraint requires that the Fisher-KPP residual R = ∂u/∂t − ∇·(D(x)∇u) − ρ·u·(1−u) ≈ 0 across Ω, subject to no-flux Neumann boundary conditions ∇u·n = 0 on ∂Ω and the initial condition u(x,0) = u₀(x) derived from the segmentation label.</p>

<h2>3.3 Project Objectives</h2>
<p><b>Objective 1:</b> Design and implement an end-to-end trainable hybrid architecture combining MONAI 3D ResNet feature extraction with three parallel prediction heads for tumor density, physics parameters, and segmentation.</p>
<p><b>Objective 2:</b> Formulate a physics-informed loss function embedding the Fisher-KPP PDE residual, initial condition, boundary condition, and physical constraint terms alongside data-driven segmentation and density regression losses.</p>
<p><b>Objective 3:</b> Develop a CFL-stable FisherKPPSolver to generate non-trivial synthetic temporal derivatives from BraTS cross-sectional data, enabling PINN training without longitudinal imaging pairs.</p>
<p><b>Objective 4:</b> Implement tissue-aware spatially heterogeneous diffusion scaling to distinguish white-matter from grey-matter tumor invasion rates in accordance with established biophysical literature.</p>
<p><b>Objective 5:</b> Evaluate the system on BraTS 2021 using standard segmentation metrics (Dice-WT/TC/ET, Hausdorff-95), physics compliance metrics (PDE residual norm), and growth prediction metrics (MSE, volume error), comparing against established baselines.</p>

<h2>3.4 Scope and Constraints</h2>
<p>The project scope is bounded to high-grade glioma (BraTS dataset, predominantly GBM), single-institution training, and the Fisher-KPP growth model. Extension to metastatic tumors, multi-institution federated settings, and alternative PDE models (Gompertz, mechanistic multiphase) is identified as future work. Hardware constraints (local GPU: 6 GB VRAM) necessitate use of ResNet-10 with 64³ spatial resolution for development, with ResNet-50 at 128³ reserved for final experiments on cloud GPU (Kaggle P100/T4).</p>
</div>
"""
